### ISSUE TITLE
Ministries to add

### ISSUE THREAD

**Issue by h313** [h313/wcec-em#1]
Children's ministry

Cross-cultural adult ministry

Community Life Bible Study

**Comment by mikey10c** [comment]
Children's Ministry:

WCEC strives to develop the young children in our church into strong
Christian believers whose faith is grounded in Christ. From praising the
Lord to reading Bible stories, the young boys and girls at WCEC have the
unique opportunity to interact with other Christians, as well as the
Heavenly Father on a daily basis. In addition to Sunday services, Friday
nights are a time of fellowship and excitement, as children engage in
activities ranging from relay races to memorizing Bible verses. Through
Cubbies, Awana, and Sunday services, our children are given the chance to
develop a stronger, more intimate relationship with Jesus Christ.

**Comment by dgodsave** [comment]
The above description of the children's ministry looks good to me until Ching-Lie provides her own description or additional information.

**Comment by dgodsave** [comment]
Community Life Bible Study - Please change to the following and make it into a ministries tab:

Tuesday Night Adult Small Group: 
Meets every other Tuesday from 7 pm to 9 pm for discussion, bible study, fellowship over food and prayer. The atmosphere is casual. The food is good. The people are friendly. All post high school adults are welcome. 
Currently meeting at Michael and Wendy Battalora's house. Please contact ________ if interested.

I'm going to confirm this with Wendy and Michael first and will get back with you.
