### ISSUE TITLE
About Page - including doctrinal statments

### ISSUE THREAD

**Issue by dgodsave** [h313/wcec-em#12]
I think the about page should have different tabs - see this church's website for an example -  http://www.hockessinumc.org/contact-us#
Tabs should include:
**Staff** - use information I already provided. We might can include some information on deacons and elders here as well but I will get back to you on that.
**Connect** - use information that is already there
**History of WCEC**
**Facility** - including info about our new building 
**Events Calendar** - could just be link to our EM and maybe YM google calendars
**Frequently asked questions** tab would also be nice for the future but we don't have worry about that now - its not essential for making the website public.
**What We believe** - Provided below:

The following information is taken from our WCEC Constitution and By-Laws. These values and policies are for both Chinese and English Congregations. Please see the document attached below for a full list of our policies and guidelines. 

**Section 1- Of the Scriptures**
We believe that the Holy Bible, as originally written, was verbally inspired and the product of
Spirit controlled men, and therefore has truth without admixture of error for its matter. We believe
that it is the true center of Christian union and the only infallible rule for all human conduct. (2 Tim.
3:16-17; 2 Peter 1:19-21)
**Section 2- Of the True God**
We believe that there is only one living and true God, infinite in every excellence; that in the
unity of the Godhead there are three personal distinctions- the Father, the Son and the Holy Spirit- yet
one in substance and equal in every divine perfection. (Exodus 20: 2-3; 1Cor. 8:6; 1Johns 5:7)
We believe in the absolute Deity of the Son, the Lord Jesus Christ; that He was divine as no
other man can be, being very God of very God, existing from all eternity co-equal with the Father and
the Spirit; that He never ceased to be God for one instant and that His humiliation did not consist in
laying aside His deity; that as a man He was miraculously begotten of the Holy Spirit and born of the
virgin Mary. (Matt. 1:20; Luke 1:26-38; John 1:1-2; 1John 5:20)
We believe that the Holy Spirit is a Divine Person, equal with the Father and Son and of the
same substance and nature; that He convicts of sin, righteousness and judgment, bears witness to the
truth, is the Agent of the New Birth and that He seals, endues, guides, teaches, witnesses to, sanctifies,
and helps the believer, indwelling every true child of God. (John 14:16-17; Romans 8:14-27; 2Cor.
13:14)
**Section 3- Of the Creation**
We believe that God created the heavens and the earth, including all life, "each after its own
kind." (Gen. 1 and 2; John 1:3; Col. 1:16-17)
**Section 4- Of the Devil, or Satan**
We believe that there is a distinct personality called Satan, that he is the unholy god of this age,
author of all darkness and sin, and is destined to the judgment of an eternal justice in the lake of fire.
(Matt. 4:1-3; 2Cor. 4:4; Rev. 20:10)
**Section 5- Of the Fall of Man**
We believe that man, in the person of the First Adam, was created in innocence but by
voluntary transgression fell into sin thus plunging the whole race into condemnation and death, so that
now all mankind is born in sin and shaped in iniquity, and become willful sinners with the first
expression of personal choice, and so are without excuse before God. (Gen. 3; Rom. 5:10-19)
**Section 6- Of the Redemption from Sin**
We believe that the only escape from the condemnation of sin is through the redemption
wrought by Jesus Christ, when He voluntarily took upon Him a human body and nature, yet without
sin, and by His suffering, death and resurrection made full satisfaction to the justice of God for the sin
of man; that the blessings of this salvation are given on the grounds of grace to all who believe and
confess that it is the immediate duty of all to accept these offers of mercy. (John 1:1-3, 14; 3:1-7; Acts
16:30-33; Heb. 10:4-14)
**Section 7- Of Salvation by Grace**
We believe that faith in the finished work of the Lord Jesus Christ is the only condition of
salvation from sin, and this salvation is wholly by grace; that no works, however good, make that
salvation more secure. (Acts 16:31; Eph. 2:8-9; Titus 3:5-7; Rom. 10:9-13)
We believe that all who take Christ as their Savior are born from above and are eternally
secure in Christ. (John 10:28-29; Rom. 8:35-39; Phil. 1:6)
**Section 8- Of the Church**
We believe that the church is established by Jesus Christ. He is the Head of the church and
the church is His body for service and His bride for glory.
We believe that the church universal is constituted of all born-again believers and is
manifested through the local church, which is a congregation of baptized believers, associated by the
covenant of faith and fellowship of the gospel; observing the ordinances of Christ; governed by His
laws; exercising the gifts, rights, and privileges invested in the church by His Word; that its officers are
Elders (including Pastors) and Deacons; that it has the absolute right of self-government directed by the
Holy Spirit and it is answerable only to Christ, and that in all matters of membership, policy,
government, discipline and benevolence the will of the local church is final. (Matt. 16:18, 18:15-17;
Acts 2:41-47; Rom. 16:26; 1Cor. 1:2, 6:4, 7:17, 11:16, 12:12-28; Eph. 1:22-23, 3:21, 4:11-12, 5:23-33;
1Thess. 4:13-18; 1Tim. 3:1-15)
**Section 9- Of the Ordinances**
We believe that there are two church ordinances; Baptism and the Lord's Supper. Baptism
sets forth in a beautiful and solemn way our faith in a crucified, buried and risen Savior, with the effects
of that faith in our lives as it produces death to sin and resurrection to a new life. The Lord's Supper,
the commemoration of our Lord's death until He comes and our continual fellowship with Him, should
be preceded by baptism and always by careful self-examination. (Acts 8:36-39; Rom. 6:3-5; 1Cor.
11:23-32)
**Section 10- Of the Righteous and Wicked**
We believe that there is a radical and essential difference between the righteous and the
wicked; that only such as through faith are justified in the name of the Lord Jesus Christ, and sanctified 
by the Spirit of God, are truly righteous in God's esteem; while all such who continue in impenitence
and unbelief are in His sight wicked, and under the curse; and that this distinction holds among men
both during life and after death, in the everlasting conscious suffering of the lost. (Mal. 3:18; Matt.
25:34-41; Luke 6:25; Rom. 6:17-23)
**Section 11- Of the Return of Christ**
We believe in the bodily, personal return of Jesus Christ. He will come to judge the living
nations and to set up His kingdom on Earth. (Matt. 25:31-46; 1Thess. 4:13-18; Rev. 19: 11-21)
**Section 12- Of the Resurrection**
We believe in the resurrection of the bodies of the dead; that believers who sleep in Jesus will
be raised at the coming of Christ; and that the wicked dead will be raised at the judgment to receive
their final doom. (John 5:21-30; 1Cor. 15:51-54; 1Thess. 4:16; Rev. 7:9-17, 20:11-15)
**Section 13- Of Marriage**
We believe in the Biblical teaching of marriage that the covenant of marriage, instituted by
God, is a union between one man and one woman. When God created mankind, He made them male
and female, and the fundamental family structure of marriage is defined as a covenantal union
between one man and one woman. Therefore, we believe that a marriage relationship between one
man and one woman, a husband and a wife, is the intended family unit established by God.
Furthermore, we believe this structure is the will of God and it is established for the well being of
human society. (Genesis 2:21-24, Matthew 19:4-6)

Attach by-laws document I will email to you

**Comment by h313** [comment]
https://h313.github.io/wcec-em/about/believe.html

I still need links to the calendars, and things to put in everything but connect.
